emissor = emissor/
recetor = recetor/

make: ${emissor}emissor.h ${recetor}recetor.h ${emissor}emissor.c ${recetor}recetor.c
	gcc ${emissor}emissor.c -o emissor.o
	gcc ${recetor}recetor.c -o recetor.o


clean:
	rm emissor.o
	rm recetor.o
